app:
  max-messages-in-chat: ${MAX_MESSAGES_IN_CHAT:20}

server:
  port: 8082

spring:
  application:
    name: chat-service
  jpa:
    open-in-view: true
    show-sql: true
  profiles:
    default: h2